Use VCR api v2
nuts-foundation/nuts-demo-ehr pull request #238
Opened 2022-03-25 12:11 UTC by reinkrul

2022-03-25 16:17 UTC, woutslakhorst commented
we also have to fix code example paths afterwards: https://github.com/nuts-foundation/nuts-workshops/search?q=nuts-demo-ehr

2022-03-25 16:20 UTC, woutslakhorst requested changes
just 1 thing and check comment on workshop code samples

2022-03-25 16:20 UTC, woutslakhorst commented on nuts/client/vcr.go
> +	result, err := c.search(ctx, query, untrusted)
We have a resolve API now to do this

2022-03-28 09:47 UTC, reinkrul commented
> we also have to fix code example paths afterwards: https://github.com/nuts-foundation/nuts-workshops/search?q=nuts-demo-ehr

Will add it to the v1 epic TODO list

2022-03-28 14:06 UTC, woutslakhorst approved these changes

2022-03-28 14:23 UTC, merged