Update dependencies
nuts-foundation/nuts-demo-ehr pull request #331
Opened 2022-11-22 09:21 UTC by reinkrul

Fixes build error

2022-11-23 13:48 UTC, gerardsn approved these changes
This increases the total number of dependencies in go.mod + go.sum by >35%. Does `go mod tidy` remove some old deps perhaps?

2022-11-23 13:48 UTC, gerardsn commented on go.mod
> +	github.com/deepmap/oapi-codegen v1.12.2
probably v1.12.3?

2022-11-23 13:49 UTC, gerardsn requested changes
Should regenerate oapi when updating the dependency

2022-11-24 15:08 UTC, reinkrul commented
Reverted

2022-11-24 15:16 UTC, merged