Irma login for customers
nuts-foundation/nuts-demo-ehr pull request #34
Opened 2021-06-09 13:25 UTC by woutslakhorst

First setup of using IRMA to enable a login.

- [ ] check customer domain with used email address in signature
- [ ] login bypass for development

2021-06-14 14:38 UTC, reinkrul requested changes
Tested, works. Some feedback on the code though.

2021-06-14 14:38 UTC, reinkrul commented
Maybe we should make the login bypass for dev the next PR as to keep things small

2021-06-15 09:50 UTC, woutslakhorst commented on api/api.yaml
> +  /web/auth/session/{sessionToken}/result:
These URLs are a 1-on-1 copy of the required IRMA URLs

2021-06-15 09:51 UTC, woutslakhorst commented on README.md
> +The Demo-EHR needs a connection to a running Nuts node. The `customers.json` file also needs to be in sync with the DIDs known to the Nuts node.
yes, as discussed, out of scope for this PR

2021-06-15 09:52 UTC, woutslakhorst commented on README.md
> +It can be configured IN THE NUTS NODE configuration file:
because I suspect people are going to look in the wrong place.

2021-06-15 09:52 UTC, woutslakhorst commented on README.md
> +When using IRMA for authentication, the Nuts node will generate a QR code with an URL in it. This URL must be publicly accessible.
no not really, it's actually json in the QR

2021-06-15 09:53 UTC, woutslakhorst commented
> Maybe we should make the login bypass for dev the next PR as to keep things small

yes I removed the todo's

2021-06-15 14:20 UTC, reinkrul approved these changes
I have some fixes (makings things simpler) in my upcomoing branch.

2021-06-16 09:39 UTC, merged